etox_microme_elastic_search:
    resource: "@EtoxMicromeElasticSearchBundle/Controller/"
    type:     annotation
    prefix:   /

etox_microme_entity2_abstract:
    resource: "@EtoxMicromeEntity2AbstractBundle/Controller/"
    type:     annotation
    prefix:   /

etox_microme_entity:
    resource: "@EtoxMicromeEntityBundle/Controller/"
    type:     annotation
    prefix:   /

etox_microme_toxic_endpoint:
    resource: "@EtoxMicromeToxicEndpointBundle/Controller/"
    type:     annotation
    prefix:   /

etox_microme_mesh_term:
    resource: "@EtoxMicromeMeshTermBundle/Controller/"
    type:     annotation
    prefix:   /

etox_microme_entity2_document:
    resource: "@EtoxMicromeEntity2DocumentBundle/Controller/"
    type:     annotation
    prefix:   /

etox_microme_document:
    resource: "@EtoxMicromeDocumentBundle/Controller/"
    type:     annotation
    prefix:   /

user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /

frontend:
    resource: "@FrontendBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"



homepage:
    pattern: /
    defaults: { _controller: FrontendBundle:Default:home }

search_interface_search:
    pattern: /search/
    defaults: { _controller: FrontendBundle:Search:search}

search_interface_inChi:
    pattern: /search/inChi/
    defaults: { _controller: FrontendBundle:Search:searchInchi, orderBy: 'hepval'}

search_interface_inChi_orderby:
    pattern: /search/inChi/{orderBy}/
    defaults: { _controller: FrontendBundle:Search:searchInchi, orderBy: 'hepval'}


elasticSearch_keyword:
    pattern: /search/keyword/{whatToSearch}/{source}/{keyword}/
    defaults: { _controller: FrontendBundle:Search:searchKeyword}

elasticSearch_keyword_orderby:
    pattern: /search/keyword/{whatToSearch}/{source}/{keyword}/orderBy/{orderBy}/
    defaults: { _controller: FrontendBundle:Search:searchKeywordOrderBy}


search_interface_search_field:
    pattern: /search/{field}/
    defaults: { _controller: FrontendBundle:Search:searchField}

search_interface_search_field_whatToSearch:
    pattern: /search/{field}/{whatToSearch}/
    defaults: { _controller: FrontendBundle:Search:searchFieldWhatToSearch}

search_interface_search_field_whatToSearch_entityType:
    pattern: /search/{field}/{whatToSearch}/{entityType}/
    defaults: { _controller: FrontendBundle:Search:searchFieldWhatToSearchEntityType}

search_interface_search_genes:
    pattern: /search/gene/{whatToSearch}/{source}/{entityName}/
    defaults: { _controller: FrontendBundle:Search:searchGene}

search_interface_search_genes_orderby:
    pattern: /search/gene/{whatToSearch}/{source}/{entityName}/orderby/{orderBy}/
    defaults: { _controller: FrontendBundle:Search:searchGeneOrderBy}

search_interface_search_field_whatToSearch_entityType_source:
    pattern: /search/{field}/{whatToSearch}/{entityType}/{source}/
    defaults: { _controller: FrontendBundle:Search:searchFieldWhatToSearchEntityTypeSource}

search_interface_search_field_whatToSearch_entityType_source_entity:
    pattern: /search/{field}/{whatToSearch}/{entityType}/{source}/{entityName}/
    defaults: { _controller: FrontendBundle:Search:searchFieldWhatToSearchEntityTypeSourceEntity, orderBy: "hepval"}

search_interface_search_field_whatToSearch_entityType_source_entity_orderby:
    pattern: /search/{field}/{whatToSearch}/{entityType}/{source}/{entityName}/orderBy/{orderBy}/
    defaults: { _controller: FrontendBundle:Search:searchFieldWhatToSearchEntityTypeSourceEntity}

view_only_curated_compounds:
    pattern: /curated/compounds/
    defaults: { _controller: FrontendBundle:OnlyCurated:viewCuratedEntities}

view_only_curated_compounds_compoundName:
    pattern: /curated/compounds/{entityName}/
    defaults: { _controller: FrontendBundle:OnlyCurated:viewCuratedEntitiesName}


autocomplete:
    pattern:    /scripts/autocomplete/
    defaults:   { _controller: FrontendBundle:Scripts:autocomplete }

export_abstracts:
    pattern:    /export-abstracts/{field}/{whatToSearch}/{entityType}/{entityName}/
    defaults:   { _controller: FrontendBundle:Search:searchFieldWhatToSearchEntityTypeEntity, orderBy: "hepval" }

export:
    pattern:    /export/{field}/{whatToSearch}/{entityType}/{source}/{entityName}/orderBy/{orderBy}/
    defaults:   { _controller: FrontendBundle:Search:searchFieldWhatToSearchEntityTypeSourceEntity, orderBy: "hepval" }

export_csv_orderby:
    pattern:    /export/{field}/{whatToSearch}/{entityType}/{source}/{entityName}/orderBy/{orderBy}/
    defaults:   { _controller: FrontendBundle:Search:searchFieldWhatToSearchEntityTypeSourceEntity}

download_route:
    pattern:  /download/{filename}/
    defaults: { _controller: FrontendBundle:Download:download }

download_sdf:
    pattern:  /download-sdf/{filename}/
    defaults: { _controller: FrontendBundle:Download:downloadsdf }

download_curated_termrelations:
    pattern:  /curated_term_relations/
    defaults: { _controller: FrontendBundle:Search:downloadCuratedTermRelations }

curate_evidences_abstract:
    pattern: /curate/abstract/{pmid}/
    defaults: { _controller: FrontendBundle:Curate:showAbstract}

ajax_entity2document_curation:
    pattern: /curate/entity2document/{entity2Document}/{action}/
    defaults: { _controller: EtoxMicromeEntity2DocumentBundle:Curation:addCurationEntity2Document}

ajax_entity2abstract_curation:
    pattern: /curate/entity2abstract/{entity2Abstract}/{action}/
    defaults: { _controller: EtoxMicromeEntity2AbstractBundle:Curation:addCurationEntity2Abstract}

ajax_compound2term2document_curation:
    pattern: /curate/compound2term2document/{compound2Term2Document}/{action}/
    defaults: { _controller: EtoxMicromeEntity2DocumentBundle:Curation:addCurationCompound2Term2Document}

ajax_compound2cyp2document_curation:
    pattern: /curate/compound2cyp2document/{compound2Cyp2Document}/{action}/
    defaults: { _controller: EtoxMicromeEntity2DocumentBundle:Curation:addCurationCompound2Cyp2Document}

ajax_compound2marker2document_curation:
    pattern: /curate/compound2marker2document/{compound2Marker2Document}/{action}/
    defaults: { _controller: EtoxMicromeEntity2DocumentBundle:Curation:addCurationCompound2Marker2Document}

ajax_cytochrome2document_curation:
    pattern: /curate/cytochrome2document/{cytochrome2Document}/{action}/
    defaults: { _controller: EtoxMicromeEntity2DocumentBundle:Curation:addCurationCytochrome2Document}

ajax_marker2document_curation:
    pattern: /curate/marker2document/{marker2Document}/{action}/
    defaults: { _controller: EtoxMicromeEntity2DocumentBundle:Curation:addCurationMarker2Document}

compound_list_summaries:
    pattern: /compound_list_summary/{id}/{initial}/orderBy/{orderBy}/
    defaults: { _controller: EtoxMicromeEntityBundle:Summaries:showSummary, initial: "a", orderBy: "drugbankname"}
    requirements:
        initial: \S

compound_list_summaries_reroute:
    pattern: /compound_list_summary/{id}/
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: compound_list_summaries
        permanent: true

compound_list_summaries_reroute_2:
    pattern: /compound_list_summary/{id}/{initial}/
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: compound_list_summaries
        permanent: true


cytochrome_list_summaries:
    pattern: /cytochrome_list_summary/{specie}/{initial}/
    defaults: { _controller: EtoxMicromeEntityBundle:Summaries:showCytochromeSummary, specie: "human"}

cytochrome_list_summaries_initial:
    pattern: /cytochrome_list_summary/{initial}/{orderBy}/
    defaults: { _controller: EtoxMicromeEntityBundle:Summaries:showCytochromeSummaryInitial}

help:
    pattern: /help/
    defaults: { _controller: FrontendBundle:Help:showHelp}

tutorial:
    pattern: /help/tutorial/
    defaults: { _controller: FrontendBundle:Help:showTutorial}

documentation:
    pattern: /help/documentacion/
    defaults: { _controller: FrontendBundle:Help:showDocumentacion}

resources:
    pattern: /resources/
    defaults: { _controller: FrontendBundle:Help:showResources}

how-to-cite:
    pattern: /how-to-cite/
    defaults: { _controller: FrontendBundle:Help:showHowToCite}

news:
    pattern: /news/
    defaults: { _controller: FrontendBundle:Default:showNews}

download_pdf:
    pattern: /download_pdf/{filename}/
    defaults: { _controller: FrontendBundle:Default:downloadPDF}

retrieve_image:
    pattern: /myimage/{image_id}/
    defaults: { _controller: EtoxMicromeEntityBundle:Image:retrieveImage }

calculate_tanimoto:
    pattern: /calculate_tanimoto/
    defaults: { _controller: EtoxMicromeEntityBundle:CompoundDict:calculateTanimoto}

cytoscape:
    pattern: /cytoscape/{entityType}/{entityName}/
    defaults: { _controller: FrontendBundle:Cytoscape:showCytoscape}

compound2cas:
    pattern: /compound_name2cas/
    defaults: { _controller: FrontendBundle:Default:compoundName2Cas}

compound2term2document2cas:
    pattern: /compound_name_relations2cas/
    defaults: { _controller: FrontendBundle:Default:compoundName2t2d2Cas}

