-- This file creates the limtox database 
-- First enter into the postgres console with
-- #change user
-- su - postgres
-- #open de postgres console
-- psql
-- #load and execute this script
-- \i /home/jcorvi/limtox_pgsql.sql
-- Database: limtox
-- 
-- DROP DATABASE limtox;
CREATE DATABASE limtox
  WITH OWNER = postgres
       ENCODING = 'UTF8'
       TABLESPACE = pg_default
       LC_COLLATE = 'en_US.UTF-8'
       LC_CTYPE = 'en_US.UTF-8'
       CONNECTION LIMIT = -1;

\connect limtox

CREATE TABLE fos_user (id INT NOT NULL, username VARCHAR(180) NOT NULL, username_canonical VARCHAR(180) NOT NULL, email VARCHAR(180) NOT NULL, email_canonical VARCHAR(180) NOT NULL, enabled BOOLEAN NOT NULL, salt VARCHAR(255) DEFAULT NULL, password VARCHAR(255) NOT NULL, last_login TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, confirmation_token VARCHAR(180) DEFAULT NULL, password_requested_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, roles TEXT NOT NULL, PRIMARY KEY(id));
CREATE UNIQUE INDEX UNIQ_957A647992FC23A8 ON fos_user (username_canonical);
CREATE UNIQUE INDEX UNIQ_957A6479A0D96FBF ON fos_user (email_canonical);
CREATE UNIQUE INDEX UNIQ_957A6479C05FB297 ON fos_user (confirmation_token);
COMMENT ON COLUMN fos_user.roles IS '(DC2Type:array)';
CREATE TABLE documentold_nephro_cardio (id INT NOT NULL, kind VARCHAR(60) NOT NULL, uid VARCHAR(255) NOT NULL, sentenceId VARCHAR(255) NOT NULL, text TEXT NOT NULL, hepval DOUBLE PRECISION DEFAULT NULL, cardval DOUBLE PRECISION DEFAULT NULL, nephval DOUBLE PRECISION DEFAULT NULL, phosval DOUBLE PRECISION DEFAULT NULL, nephroval DOUBLE PRECISION DEFAULT NULL, cardioval DOUBLE PRECISION DEFAULT NULL, thyroval DOUBLE PRECISION DEFAULT NULL, phosphoval DOUBLE PRECISION DEFAULT NULL, patternCount DOUBLE PRECISION DEFAULT NULL, ruleScore DOUBLE PRECISION DEFAULT NULL, hepTermNormScore DOUBLE PRECISION DEFAULT NULL, hepTermVarScore DOUBLE PRECISION DEFAULT NULL, svmConfidence DOUBLE PRECISION DEFAULT NULL, created TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id));
CREATE INDEX documentold_uid_index ON documentold_nephro_cardio (uid);
CREATE INDEX documentold_kind_index ON documentold_nephro_cardio (kind);
CREATE INDEX documentold_sentenceId_index ON documentold_nephro_cardio (sentenceId);
CREATE INDEX documentold_hepval_index ON documentold_nephro_cardio (hepval);
CREATE INDEX documentold_cardval_index ON documentold_nephro_cardio (cardval);
CREATE INDEX documentold_nephval_index ON documentold_nephro_cardio (nephval);
CREATE INDEX documentold_phosval_index ON documentold_nephro_cardio (phosval);
CREATE INDEX documentold_patterncount_index ON documentold_nephro_cardio (patternCount);
CREATE INDEX documentold_rulescore_index ON documentold_nephro_cardio (ruleScore);
CREATE INDEX documentold_nephroval_index ON documentold_nephro_cardio (nephroval);
CREATE INDEX documentold_cardioval_index ON documentold_nephro_cardio (cardioval);
CREATE INDEX documentold_tyroval_index ON documentold_nephro_cardio (thyroval);
CREATE INDEX documentold_phosphoval_index ON documentold_nephro_cardio (phosphoval);
CREATE INDEX documentold_heptermvar_index ON documentold_nephro_cardio (hepTermVarScore);
CREATE INDEX documentold_heptermnorm_index ON documentold_nephro_cardio (hepTermNormScore);
CREATE INDEX documentold_svm_confidence_index ON documentold_nephro_cardio (svmConfidence);
CREATE TABLE DocumentWithMarker (id INT NOT NULL, kind VARCHAR(60) NOT NULL, uid VARCHAR(255) NOT NULL, sentenceId VARCHAR(255) NOT NULL, text TEXT NOT NULL, hepval DOUBLE PRECISION DEFAULT NULL, cardval DOUBLE PRECISION DEFAULT NULL, nephval DOUBLE PRECISION DEFAULT NULL, phosval DOUBLE PRECISION DEFAULT NULL, patternCount DOUBLE PRECISION DEFAULT NULL, ruleScore DOUBLE PRECISION DEFAULT NULL, hepTermNormScore DOUBLE PRECISION DEFAULT NULL, hepTermVarScore DOUBLE PRECISION DEFAULT NULL, svmConfidence DOUBLE PRECISION DEFAULT NULL, created TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id));
CREATE INDEX documentWithMarker_uid_index ON DocumentWithMarker (uid);
CREATE INDEX documentWithMarker_kind_index ON DocumentWithMarker (kind);
CREATE INDEX documentWithMarker_sentenceId_index ON DocumentWithMarker (sentenceId);
CREATE INDEX documentWithMarker_hepval_index ON DocumentWithMarker (hepval);
CREATE INDEX documentWithMarker_cardval_index ON DocumentWithMarker (cardval);
CREATE INDEX documentWithMarker_nephval_index ON DocumentWithMarker (nephval);
CREATE INDEX documentWithMarker_phosval_index ON DocumentWithMarker (phosval);
CREATE INDEX documentWithMarker_patterncount ON DocumentWithMarker (patternCount);
CREATE INDEX documentWithMarker_rulescore ON DocumentWithMarker (ruleScore);
CREATE INDEX documentWithMarker_heptermnormscore ON DocumentWithMarker (hepTermNormScore);
CREATE INDEX documentWithMarker_heptermvarscore ON DocumentWithMarker (hepTermVarScore);
CREATE INDEX documentWithMarker_svmconfidence ON DocumentWithMarker (svmConfidence);
CREATE TABLE DocumentWithCytochrome (id INT NOT NULL, kind VARCHAR(60) NOT NULL, uid VARCHAR(255) NOT NULL, sentenceId VARCHAR(255) NOT NULL, text TEXT NOT NULL, hepval DOUBLE PRECISION DEFAULT NULL, cardval DOUBLE PRECISION DEFAULT NULL, nephval DOUBLE PRECISION DEFAULT NULL, phosval DOUBLE PRECISION DEFAULT NULL, patternCount DOUBLE PRECISION DEFAULT NULL, ruleScore DOUBLE PRECISION DEFAULT NULL, hepTermNormScore DOUBLE PRECISION DEFAULT NULL, hepTermVarScore DOUBLE PRECISION DEFAULT NULL, svmConfidence DOUBLE PRECISION DEFAULT NULL, created TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id));
CREATE INDEX documentWithCytochrome_uid_index ON DocumentWithCytochrome (uid);
CREATE INDEX documentWithCytochrome_kind_index ON DocumentWithCytochrome (kind);
CREATE INDEX documentWithCytochrome_sentenceId_index ON DocumentWithCytochrome (sentenceId);
CREATE INDEX documentWithCytochrome_hepval_index ON DocumentWithCytochrome (hepval);
CREATE INDEX documentWithCytochrome_cardval_index ON DocumentWithCytochrome (cardval);
CREATE INDEX documentWithCytochrome_nephval_index ON DocumentWithCytochrome (nephval);
CREATE INDEX documentWithCytochrome_phosval_index ON DocumentWithCytochrome (phosval);
CREATE INDEX documentWithCytochrome_patterncount ON DocumentWithCytochrome (patternCount);
CREATE INDEX documentWithCytochrome_rulescore ON DocumentWithCytochrome (ruleScore);
CREATE INDEX documentWithCytochrome_heptermnormscore ON DocumentWithCytochrome (hepTermNormScore);
CREATE INDEX documentWithCytochrome_heptermvarscore ON DocumentWithCytochrome (hepTermVarScore);
CREATE INDEX documentWithCytochrome_svmconfidence ON DocumentWithCytochrome (svmConfidence);
CREATE TABLE Image (id INT NOT NULL, compound INT NOT NULL, image BYTEA NOT NULL, PRIMARY KEY(id));
CREATE TABLE DocumentWithCompound (id INT NOT NULL, kind VARCHAR(60) NOT NULL, uid VARCHAR(255) NOT NULL, sentenceId VARCHAR(255) NOT NULL, text TEXT NOT NULL, hepval DOUBLE PRECISION DEFAULT NULL, cardval DOUBLE PRECISION DEFAULT NULL, nephval DOUBLE PRECISION DEFAULT NULL, phosval DOUBLE PRECISION DEFAULT NULL, patternCount DOUBLE PRECISION DEFAULT NULL, ruleScore DOUBLE PRECISION DEFAULT NULL, hepTermNormScore DOUBLE PRECISION DEFAULT NULL, hepTermVarScore DOUBLE PRECISION DEFAULT NULL, svmConfidence DOUBLE PRECISION DEFAULT NULL, created TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id));
CREATE INDEX documentWithCompound_uid ON DocumentWithCompound (uid);
CREATE INDEX documentWithCompound_kind ON DocumentWithCompound (kind);
CREATE INDEX documentWithCompound_sentenceId ON DocumentWithCompound (sentenceId);
CREATE INDEX documentWithCompound_hepval ON DocumentWithCompound (hepval);
CREATE INDEX documentWithCompound_cardval ON DocumentWithCompound (cardval);
CREATE INDEX documentWithCompound_nephval ON DocumentWithCompound (nephval);
CREATE INDEX documentWithCompound_phosval ON DocumentWithCompound (phosval);
CREATE INDEX documentWithCompound_patterncount ON DocumentWithCompound (patternCount);
CREATE INDEX documentWithCompound_rulescore ON DocumentWithCompound (ruleScore);
CREATE INDEX documentWithCompound_heptermnormscore ON DocumentWithCompound (hepTermNormScore);
CREATE INDEX documentWithCompound_heptermvarscore ON DocumentWithCompound (hepTermVarScore);
CREATE INDEX documentWithCompound_svmconfidence ON DocumentWithCompound (svmConfidence);
CREATE TABLE AbstractWithCompound (id INT NOT NULL, pmid VARCHAR(255) NOT NULL, title TEXT NOT NULL, text TEXT NOT NULL, hepval DOUBLE PRECISION DEFAULT NULL, patternCount DOUBLE PRECISION DEFAULT NULL, ruleScore DOUBLE PRECISION DEFAULT NULL, hepTermNormScore DOUBLE PRECISION DEFAULT NULL, hepTermVarScore DOUBLE PRECISION DEFAULT NULL, svmConfidence DOUBLE PRECISION DEFAULT NULL, toxicology INT DEFAULT NULL, biomarker INT DEFAULT NULL, created TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id));
CREATE INDEX abstractWithCompound_pmid_index ON AbstractWithCompound (pmid);
CREATE INDEX abstractWithCompound_hepval_index ON AbstractWithCompound (hepval);
CREATE INDEX abstractWithCompound_patterncount ON AbstractWithCompound (patternCount);
CREATE INDEX abstractWithCompound_rulescore ON AbstractWithCompound (ruleScore);
CREATE INDEX abstractWithCompound_heptermnormscore ON AbstractWithCompound (hepTermNormScore);
CREATE INDEX abstractWithCompound_heptermvarscore ON AbstractWithCompound (hepTermVarScore);
CREATE INDEX abstractWithCompound_svmconfidence ON AbstractWithCompound (svmConfidence);
CREATE TABLE Abstracts (id INT NOT NULL, pmid VARCHAR(255) NOT NULL, title TEXT NOT NULL, text TEXT NOT NULL, hepval DOUBLE PRECISION DEFAULT NULL, patternCount DOUBLE PRECISION DEFAULT NULL, ruleScore DOUBLE PRECISION DEFAULT NULL, hepTermNormScore DOUBLE PRECISION DEFAULT NULL, hepTermVarScore DOUBLE PRECISION DEFAULT NULL, svmConfidence DOUBLE PRECISION DEFAULT NULL, toxicology INT DEFAULT NULL, biomarker INT DEFAULT NULL, created TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id));
CREATE INDEX abstracts_pmid_index ON Abstracts (pmid);
CREATE INDEX abstracts_hepval_index ON Abstracts (hepval);
CREATE INDEX abstracts_patterncount_index ON Abstracts (patternCount);
CREATE INDEX abstracts_rulescore_index ON Abstracts (ruleScore);
CREATE INDEX abstracts_heptermvar_index ON Abstracts (hepTermVarScore);
CREATE INDEX abstracts_heptermnorm_index ON Abstracts (hepTermNormScore);
CREATE INDEX abstracts_svm_confidence_index ON Abstracts (svmConfidence);
CREATE TABLE Marker (id INT NOT NULL, entityId VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, markerType VARCHAR(255) NOT NULL, tax VARCHAR(255) NOT NULL, term1 VARCHAR(255) NOT NULL, term2 VARCHAR(255) DEFAULT NULL, created TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id));
CREATE INDEX marker_entity_index ON Marker (entityId);
CREATE INDEX marker_name_index ON Marker (name);
CREATE INDEX marker_markerType_index ON Marker (markerType);
CREATE TABLE EntityRanking (id INT NOT NULL, entityId VARCHAR(255) NOT NULL, meanHepval DOUBLE PRECISION NOT NULL, sumHepval DOUBLE PRECISION NOT NULL, numDocuments INT NOT NULL, numRelArticles INT NOT NULL, meanRelHepval DOUBLE PRECISION NOT NULL, created TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id));
CREATE INDEX entityRanking_entity_index ON EntityRanking (entityId);
CREATE TABLE tanimotovalues_new (id INT NOT NULL, idcompound1 INT DEFAULT NULL, idcompound2 INT DEFAULT NULL, smile1 TEXT DEFAULT NULL, smile2 TEXT DEFAULT NULL, inChi1 TEXT DEFAULT NULL, inChi2 TEXT DEFAULT NULL, tanimoto DOUBLE PRECISION DEFAULT NULL, created TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id));
CREATE INDEX tanimotovalues_idcompound1_index ON tanimotovalues_new (idcompound1);
CREATE INDEX tanimotovalues_idcompound2_index ON tanimotovalues_new (idcompound2);
CREATE INDEX tanimotovalues_tanimoto_index ON tanimotovalues_new (tanimoto);
CREATE TABLE GeneSpecie (id INT NOT NULL, gene_id INT DEFAULT NULL, specie_id INT DEFAULT NULL, created TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id));
CREATE INDEX IDX_29B1CC6838BEE1C3 ON GeneSpecie (gene_id);
CREATE INDEX IDX_29B1CC68D5436AB7 ON GeneSpecie (specie_id);
CREATE TABLE Drugbank (id INT NOT NULL, drugbankid VARCHAR(10) NOT NULL, drugbankname VARCHAR(255) NOT NULL, approval VARCHAR(255) NOT NULL, category VARCHAR(255) NOT NULL, target_relation TEXT NOT NULL, hepval_counter INT DEFAULT NULL, svm_confidence_counter INT DEFAULT NULL, pattern_counter INT DEFAULT NULL, term_counter INT DEFAULT NULL, rule_counter INT DEFAULT NULL, total_mentions INT DEFAULT NULL, PRIMARY KEY(id));
CREATE TABLE MarkerType (id INT NOT NULL, type VARCHAR(255) NOT NULL, created TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id));
CREATE TABLE Alias (id INT NOT NULL, name VARCHAR(500) NOT NULL, alias TEXT DEFAULT NULL, created TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id));
CREATE INDEX alias_name_index ON Alias (name);
CREATE TABLE GeneDictionary (id INT NOT NULL, gene_id VARCHAR(255) NOT NULL, gene_name VARCHAR(512) NOT NULL, tax_id INT NOT NULL, PRIMARY KEY(id));
CREATE INDEX geneDictionary_gene_id_index ON GeneDictionary (gene_id);
CREATE INDEX geneDictionary_gene_name_index ON GeneDictionary (gene_name);
CREATE TABLE GoTerm (id INT NOT NULL, entityId VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, goClass VARCHAR(255) NOT NULL, nameType VARCHAR(255) NOT NULL, manualValidation VARCHAR(255) NOT NULL, depth INT NOT NULL, scoreSum DOUBLE PRECISION NOT NULL, scoreMean DOUBLE PRECISION NOT NULL, scoreFract DOUBLE PRECISION NOT NULL, scoreAnnot DOUBLE PRECISION NOT NULL, created TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id));
CREATE INDEX goTerm_entity_index ON GoTerm (entityId);
CREATE INDEX goTerm_name_index ON GoTerm (name);
CREATE TABLE MolecularMechanism (id INT NOT NULL, entityId VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, type VARCHAR(255) NOT NULL, created TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id));
CREATE INDEX molecularMechanism_entity_index ON MolecularMechanism (entityId);
CREATE INDEX molecularMechanism_name_index ON MolecularMechanism (name);
CREATE TABLE Specie (id INT NOT NULL, ncbiTaxId VARCHAR(255) NOT NULL, entityId VARCHAR(255) NOT NULL, specieCategory VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, nameClass VARCHAR(255) NOT NULL, specieTox VARCHAR(255) NOT NULL, created TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id));
CREATE INDEX specie_entity_index ON Specie (entityId);
CREATE INDEX specie_name_index ON Specie (name);
CREATE TABLE AdverseEffect (id INT NOT NULL, entityId VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, type VARCHAR(255) NOT NULL, extId1 VARCHAR(255) NOT NULL, extId2 VARCHAR(255) NOT NULL, created TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id));
CREATE INDEX adeverseEffect_entity_index ON AdverseEffect (entityId);
CREATE INDEX adeverseEffect_name_index ON AdverseEffect (name);
CREATE TABLE HepatotoxKeyword (id INT NOT NULL, validated INT NOT NULL, term VARCHAR(500) NOT NULL, norm VARCHAR(500) NOT NULL, pos VARCHAR(500) NOT NULL, EFPIA VARCHAR(30) DEFAULT NULL, COSTART VARCHAR(30) DEFAULT NULL, MedDRA VARCHAR(30) DEFAULT NULL, MPheno VARCHAR(30) DEFAULT NULL, adverseEvents VARCHAR(30) DEFAULT NULL, "do" VARCHAR(30) DEFAULT NULL, geminaSymptom VARCHAR(30) DEFAULT NULL, humanPhenotype VARCHAR(30) DEFAULT NULL, mpath VARCHAR(30) DEFAULT NULL, MESH_OMIM VARCHAR(30) DEFAULT NULL, polysearch VARCHAR(30) DEFAULT NULL, etox VARCHAR(30) DEFAULT NULL, created TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id));
CREATE INDEX hepatotoxKeyword_term_index ON HepatotoxKeyword (term);
CREATE INDEX hepatotoxKeyword_norm_index ON HepatotoxKeyword (norm);
CREATE INDEX hepatotoxKeyword_pos_index ON HepatotoxKeyword (pos);
CREATE INDEX hepatotoxKeyword_EFPIA_index ON HepatotoxKeyword (EFPIA);
CREATE INDEX hepatotoxKeyword_COSTART_index ON HepatotoxKeyword (COSTART);
CREATE INDEX hepatotoxKeyword_MedDRA_index ON HepatotoxKeyword (MedDRA);
CREATE INDEX hepatotoxKeyword_MPheno_index ON HepatotoxKeyword (MPheno);
CREATE INDEX hepatotoxKeyword_adverse_events_index ON HepatotoxKeyword (adverseEvents);
CREATE INDEX hepatotoxKeyword_do_index ON HepatotoxKeyword ("do");
CREATE INDEX hepatotoxKeyword_gemina_symptom_index ON HepatotoxKeyword (geminaSymptom);
CREATE INDEX hepatotoxKeyword_human_phenotype_index ON HepatotoxKeyword (humanPhenotype);
CREATE INDEX hepatotoxKeyword_mpath_index ON HepatotoxKeyword (mpath);
CREATE INDEX hepatotoxKeyword_MESH_OMIM_index ON HepatotoxKeyword (MESH_OMIM);
CREATE INDEX hepatotoxKeyword_polysearch_index ON HepatotoxKeyword (polysearch);
CREATE INDEX hepatotoxKeyword_etox_index ON HepatotoxKeyword (etox);
CREATE TABLE Gene (id INT NOT NULL, entityId VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, type VARCHAR(255) NOT NULL, ncbi_tax VARCHAR(255) NOT NULL, extId1 VARCHAR(255) NOT NULL, extId2 VARCHAR(255) NOT NULL, created TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id));
CREATE INDEX gene_entity_index ON Gene (entityId);
CREATE INDEX gene_name_index ON Gene (name);
CREATE TABLE CompoundMesh (id INT NOT NULL, name VARCHAR(255) NOT NULL, identifier VARCHAR(255) NOT NULL, meshUi VARCHAR(255) NOT NULL, created TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id));
CREATE INDEX compoundMesh_name_index ON CompoundMesh (name);
CREATE INDEX compoundMesh_meshUi_index ON CompoundMesh (meshUi);
CREATE TABLE CompoundDict (id INT NOT NULL, image_id INT DEFAULT NULL, structure_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, chemIdPlus VARCHAR(500) NOT NULL, chebi VARCHAR(500) NOT NULL, casRegistryNumber VARCHAR(500) NOT NULL, pubChemCompound VARCHAR(500) NOT NULL, pubChemSubstance VARCHAR(500) DEFAULT NULL, inChi TEXT DEFAULT NULL, drugBank VARCHAR(500) DEFAULT NULL, humanMetabolome VARCHAR(500) DEFAULT NULL, keggCompound VARCHAR(500) DEFAULT NULL, keggDrug VARCHAR(500) DEFAULT NULL, mesh VARCHAR(500) DEFAULT NULL, nrDbIds INT DEFAULT NULL, smile TEXT NOT NULL, name2struct INT DEFAULT NULL, created TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id));
CREATE UNIQUE INDEX UNIQ_88A1CD3C3DA5256D ON CompoundDict (image_id);
CREATE UNIQUE INDEX UNIQ_88A1CD3C2534008B ON CompoundDict (structure_id);
CREATE INDEX compoundDict_new_name_index ON CompoundDict (name);
CREATE INDEX compoundDict_new_chemIdPlus_index ON CompoundDict (chemIdPlus);
CREATE INDEX compoundDict_new_chebi_index ON CompoundDict (chebi);
CREATE INDEX compoundDict_new_inchi_index ON CompoundDict (inChi);
CREATE INDEX compoundDict_new_casRegistryNumber_index ON CompoundDict (casRegistryNumber);
CREATE INDEX compoundDict_new_pubChemCompound_index ON CompoundDict (pubChemCompound);
CREATE INDEX compoundDict_new_pubChemSubstance_index ON CompoundDict (pubChemSubstance);
CREATE INDEX compoundDict_new_drugBank_index ON CompoundDict (drugBank);
CREATE INDEX compoundDict_new_humanMetabolome_index ON CompoundDict (humanMetabolome);
CREATE INDEX compoundDict_new_keggCompound_index ON CompoundDict (keggCompound);
CREATE INDEX compoundDict_new_keggDrug_index ON CompoundDict (keggDrug);
CREATE INDEX compoundDict_new_mesh_index ON CompoundDict (mesh);
CREATE TABLE Enzyme (id INT NOT NULL, entityId VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, extId1 VARCHAR(255) NOT NULL, extId2 VARCHAR(255) NOT NULL, extId3 VARCHAR(255) NOT NULL, extId4 VARCHAR(255) NOT NULL, created TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id));
CREATE INDEX enzyme_entity_index ON Enzyme (entityId);
CREATE INDEX enzyme_name_index ON Enzyme (name);
CREATE TABLE OrganTissue (id INT NOT NULL, entityId VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, type VARCHAR(255) NOT NULL, extId1 VARCHAR(255) NOT NULL, extId2 VARCHAR(255) NOT NULL, created TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id));
CREATE INDEX organTissue_entity_index ON OrganTissue (entityId);
CREATE INDEX organTissue_name_index ON OrganTissue (name);
CREATE TABLE HepatotoxTrigger (id INT NOT NULL, entityId VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, type VARCHAR(255) NOT NULL, created TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id));
CREATE INDEX hepatotoxTrigger_entity_index ON HepatotoxTrigger (entityId);
CREATE INDEX hepatotoxTrigger_name_index ON HepatotoxTrigger (name);
CREATE TABLE CypsUniprotRanking (id INT NOT NULL, uniprotAccession VARCHAR(255) NOT NULL, ranking INT NOT NULL, PRIMARY KEY(id));
CREATE TABLE CellType (id INT NOT NULL, entityId VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, type VARCHAR(255) NOT NULL, extId1 VARCHAR(255) NOT NULL, extId2 VARCHAR(255) NOT NULL, created TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id));
CREATE INDEX cellType_entity_index ON CellType (entityId);
CREATE INDEX cellType_name_index ON CellType (name);
CREATE TABLE Cytochrome (id INT NOT NULL, entityId VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, type VARCHAR(255) NOT NULL, tax VARCHAR(255) NOT NULL, score DOUBLE PRECISION NOT NULL, canonical VARCHAR(255) NOT NULL, cypUniprotRanking DOUBLE PRECISION DEFAULT NULL, created TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id));
CREATE INDEX cytochrome_entity_index ON Cytochrome (entityId);
CREATE INDEX cytochrome_name_index ON Cytochrome (name);
CREATE INDEX cytochrome_tax_index ON Cytochrome (tax);
CREATE TABLE Structure (id INT NOT NULL, compound INT DEFAULT NULL, sdf TEXT DEFAULT NULL, mol TEXT DEFAULT NULL, pathtosdf TEXT DEFAULT NULL, created TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id));
CREATE TABLE compound2marker2document_new (id INT NOT NULL, document_id INT DEFAULT NULL, sentenceId VARCHAR(200) NOT NULL, compoundName VARCHAR(800) NOT NULL, liverMarkerName VARCHAR(500) NOT NULL, relationScore DOUBLE PRECISION NOT NULL, relationQualifier VARCHAR(2) NOT NULL, relationType VARCHAR(500) NOT NULL, relationEvidence TEXT NOT NULL, sentence TEXT NOT NULL, compoundQualifier INT NOT NULL, curation INT DEFAULT NULL, created TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id));
CREATE INDEX compound2Marker2Document_sentenceId_index_new ON compound2marker2document_new (sentenceId);
CREATE INDEX compound2Marker2Document_compound_index_new ON compound2marker2document_new (compoundName);
CREATE INDEX compound2Marker2Document_liverMarkerName_index_new ON compound2marker2document_new (liverMarkerName);
CREATE INDEX compound2marker2document_document_id_new ON compound2marker2document_new (document_id);
CREATE INDEX compound2marker2document_relation_score_new ON compound2marker2document_new (relationScore);
CREATE INDEX compound2marker2document_relation_type_new ON compound2marker2document_new (relationType);
CREATE INDEX compound2marker2document_curation_new ON compound2marker2document_new (curation);
CREATE TABLE HepKeywordTermNorm2Document (id INT NOT NULL, document_id INT DEFAULT NULL, hepKeywordNorm VARCHAR(500) NOT NULL, kind VARCHAR(60) NOT NULL, curation INT DEFAULT NULL, created TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id));
CREATE INDEX IDX_1C19BCD0C33F7837 ON HepKeywordTermNorm2Document (document_id);
CREATE INDEX hepKeywordTermNorm_kind_index ON HepKeywordTermNorm2Document (kind);
CREATE TABLE cytochrome2document_new (id INT NOT NULL, document_id INT DEFAULT NULL, tagMethod VARCHAR(255) NOT NULL, baseName VARCHAR(255) NOT NULL, rootName VARCHAR(255) NOT NULL, cypsMention VARCHAR(255) NOT NULL, sentence TEXT NOT NULL, cypsCanonical VARCHAR(255) NOT NULL, curation INT DEFAULT NULL, hepval DOUBLE PRECISION DEFAULT NULL, patternCount DOUBLE PRECISION DEFAULT NULL, ruleScore DOUBLE PRECISION DEFAULT NULL, hepTermNormScore DOUBLE PRECISION DEFAULT NULL, hepTermVarScore DOUBLE PRECISION DEFAULT NULL, svmConfidence DOUBLE PRECISION DEFAULT NULL, created TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id));
CREATE INDEX IDX_21C7FD7C33F7837 ON cytochrome2document_new (document_id);
CREATE INDEX cytochrome2Document_tagMethod_index_new ON cytochrome2document_new (tagMethod);
CREATE INDEX cytochrome2Document_cypsMention_index_new ON cytochrome2document_new (cypsMention);
CREATE INDEX cytochrome2Document_hepval_new ON cytochrome2document_new (hepval);
CREATE INDEX cytochrome2Document_patterncount_new ON cytochrome2document_new (patternCount);
CREATE INDEX cytochrome2Document_rulescore_new ON cytochrome2document_new (ruleScore);
CREATE INDEX cytochrome2Document_heptermnormscore_new ON cytochrome2document_new (hepTermNormScore);
CREATE INDEX cytochrome2Document_heptermvarscore_new ON cytochrome2document_new (hepTermVarScore);
CREATE INDEX cytochrome2Document_svmconfidence_new ON cytochrome2document_new (svmConfidence);
CREATE TABLE Specie2Document (id INT NOT NULL, document_id INT DEFAULT NULL, specie_id INT DEFAULT NULL, hepval DOUBLE PRECISION DEFAULT NULL, cardval DOUBLE PRECISION DEFAULT NULL, nephval DOUBLE PRECISION DEFAULT NULL, phosval DOUBLE PRECISION DEFAULT NULL, patternCount DOUBLE PRECISION DEFAULT NULL, ruleScore DOUBLE PRECISION DEFAULT NULL, hepTermNormScore DOUBLE PRECISION DEFAULT NULL, hepTermVarScore DOUBLE PRECISION DEFAULT NULL, svmConfidence DOUBLE PRECISION DEFAULT NULL, created TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id));
CREATE INDEX specie2Document_document_index ON Specie2Document (document_id);
CREATE INDEX specie2Document_specie_index ON Specie2Document (specie_id);
CREATE INDEX specie2document_patterncount ON Specie2Document (patternCount);
CREATE INDEX specie2document_rulescore ON Specie2Document (ruleScore);
CREATE INDEX specie2document_heptermnormscore ON Specie2Document (hepTermNormScore);
CREATE INDEX specie2document_heptermvarscore ON Specie2Document (hepTermVarScore);
CREATE INDEX specie2document_svmconfidence ON Specie2Document (svmConfidence);
CREATE TABLE compound2term2document_new (id INT NOT NULL, document_id INT DEFAULT NULL, sentenceId VARCHAR(200) NOT NULL, compoundName VARCHAR(800) NOT NULL, term VARCHAR(500) NOT NULL, relationScore DOUBLE PRECISION NOT NULL, relationQualifier VARCHAR(2) NOT NULL, relationType VARCHAR(500) NOT NULL, relationEvidence TEXT NOT NULL, sentence TEXT NOT NULL, compoundQualifier INT NOT NULL, curation INT DEFAULT NULL, hepval DOUBLE PRECISION DEFAULT NULL, cardval DOUBLE PRECISION DEFAULT NULL, nephval DOUBLE PRECISION DEFAULT NULL, phosval DOUBLE PRECISION DEFAULT NULL, patternCount DOUBLE PRECISION DEFAULT NULL, ruleScore DOUBLE PRECISION DEFAULT NULL, hepTermNormScore DOUBLE PRECISION DEFAULT NULL, hepTermVarScore DOUBLE PRECISION DEFAULT NULL, svmConfidence DOUBLE PRECISION DEFAULT NULL, compound2TermConfidence DOUBLE PRECISION DEFAULT NULL, created TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id));
CREATE INDEX compound2term2document_sentenceId_index_new ON compound2term2document_new (sentenceId);
CREATE INDEX compound2term2document_compound_index_new ON compound2term2document_new (compoundName);
CREATE INDEX compound2term2document_term_index_new ON compound2term2document_new (term);
CREATE INDEX compound2term2document_document_id_new ON compound2term2document_new (document_id);
CREATE INDEX compound2term2document_relation_score_new ON compound2term2document_new (relationScore);
CREATE INDEX compound2term2document_curation_new ON compound2term2document_new (curation);
CREATE TABLE HepKeywordTermVariant2Document (id INT NOT NULL, document_id INT DEFAULT NULL, termVariant VARCHAR(800) NOT NULL, hepKeywordTerm VARCHAR(500) NOT NULL, hepKeywordNorm VARCHAR(500) NOT NULL, kind VARCHAR(60) NOT NULL, curation INT DEFAULT NULL, created TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id));
CREATE INDEX IDX_A316E36BC33F7837 ON HepKeywordTermVariant2Document (document_id);
CREATE INDEX hepKeywordTermVariant_termVariant_index ON HepKeywordTermVariant2Document (termVariant);
CREATE INDEX hepKeywordTermVariant_hepKeywordTerm_index ON HepKeywordTermVariant2Document (hepKeywordTerm);
CREATE INDEX hepKeywordTermVariant_hepKeywordNorm_index ON HepKeywordTermVariant2Document (hepKeywordNorm);
CREATE INDEX hepKeywordTermVariant_kind_index ON HepKeywordTermVariant2Document (kind);
CREATE TABLE compound2cyp2document_new (id INT NOT NULL, document_id INT DEFAULT NULL, sentenceId VARCHAR(200) NOT NULL, compoundName VARCHAR(800) NOT NULL, cypsMention VARCHAR(200) NOT NULL, patternRelation VARCHAR(15) NOT NULL, patternEvidence TEXT NOT NULL, cypsCanonical VARCHAR(50) NOT NULL, sentence TEXT NOT NULL, svmInduction VARCHAR(15) NOT NULL, svmInhibition VARCHAR(15) NOT NULL, svmMetabolism VARCHAR(15) NOT NULL, inductionScore INT NOT NULL, inhibitionScore INT NOT NULL, metabolismScore INT NOT NULL, sumScore INT NOT NULL, relationQualifier VARCHAR(2) NOT NULL, compoundQualifier INT NOT NULL, curation INT DEFAULT NULL, created TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id));
CREATE INDEX compound2cyp2document_sentenceId_index_new ON compound2cyp2document_new (sentenceId);
CREATE INDEX compound2Cyp2Document_compound_name_index_new ON compound2cyp2document_new (compoundName);
CREATE INDEX compound2Cyp2Document_cyp_index_new ON compound2cyp2document_new (cypsMention);
CREATE INDEX compound2cyp2document_document_id_new ON compound2cyp2document_new (document_id);
CREATE INDEX compound2cyp2document_inhibition_new ON compound2cyp2document_new (inhibitionScore);
CREATE INDEX compound2cyp2document_induction_new ON compound2cyp2document_new (inductionScore);
CREATE INDEX compound2cyp2document_metabolism_new ON compound2cyp2document_new (metabolismScore);
CREATE INDEX compound2cyp2document_svm_inhibition_new ON compound2cyp2document_new (svmInhibition);
CREATE INDEX compound2cyp2document_svm_induction_new ON compound2cyp2document_new (svmInduction);
CREATE INDEX compound2cyp2document_svm_metabolism_new ON compound2cyp2document_new (svmMetabolism);
CREATE INDEX compound2cyp2document_curation_new ON compound2cyp2document_new (curation);
CREATE TABLE entity2document_nephro_cardio (id INT NOT NULL, document_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, qualifier VARCHAR(60) NOT NULL, tagMethod VARCHAR(255) DEFAULT NULL, curation INT DEFAULT NULL, hepval DOUBLE PRECISION DEFAULT NULL, cardval DOUBLE PRECISION DEFAULT NULL, nephval DOUBLE PRECISION DEFAULT NULL, phosval DOUBLE PRECISION DEFAULT NULL, nephroval DOUBLE PRECISION DEFAULT NULL, cardioval DOUBLE PRECISION DEFAULT NULL, thyroval DOUBLE PRECISION DEFAULT NULL, phosphoval DOUBLE PRECISION DEFAULT NULL, patternCount DOUBLE PRECISION DEFAULT NULL, ruleScore DOUBLE PRECISION DEFAULT NULL, hepTermNormScore DOUBLE PRECISION DEFAULT NULL, hepTermVarScore DOUBLE PRECISION DEFAULT NULL, svmConfidence DOUBLE PRECISION DEFAULT NULL, kind VARCHAR(255) NOT NULL, created TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id));
CREATE INDEX entity2Document_nephro_cardio_document_id_new ON entity2document_nephro_cardio (document_id);
CREATE INDEX entity2Document_nephro_cardio_name_index_new ON entity2document_nephro_cardio (name);
CREATE INDEX entity2Document_nephro_cardio_curation_new ON entity2document_nephro_cardio (curation);
CREATE INDEX entity2document_nephro_cardio_hepval_new ON entity2document_nephro_cardio (hepval);
CREATE INDEX entity2document_nephro_cardio_cardval_new ON entity2document_nephro_cardio (cardval);
CREATE INDEX entity2document_nephro_cardio_nephval_new ON entity2document_nephro_cardio (nephval);
CREATE INDEX entity2document_nephro_cardio_phosval_new ON entity2document_nephro_cardio (phosval);
CREATE INDEX entity2document_nephro_cardio_nephroval_index ON entity2document_nephro_cardio (nephroval);
CREATE INDEX entity2document_nephro_cardio_cardioval_index ON entity2document_nephro_cardio (cardioval);
CREATE INDEX entity2document_nephro_cardio_thyroval_index ON entity2document_nephro_cardio (thyroval);
CREATE INDEX entity2document_nephro_cardio_phosphoval_index ON entity2document_nephro_cardio (phosphoval);
CREATE INDEX entity2document_nephro_cardio_patterncount_new ON entity2document_nephro_cardio (patternCount);
CREATE INDEX entity2document_nephro_cardio_rulescore_new ON entity2document_nephro_cardio (ruleScore);
CREATE INDEX entity2document_nephro_cardio_qualifier_new ON entity2document_nephro_cardio (qualifier);
CREATE INDEX entity2document_nephro_cardio_svm_confidence_index_new ON entity2document_nephro_cardio (svmConfidence);
CREATE INDEX entity2document_nephro_cardio_heptermnormscore_new ON entity2document_nephro_cardio (hepTermNormScore);
CREATE INDEX entity2document_nephro_cardio_heptermvarscore_new ON entity2document_nephro_cardio (hepTermVarScore);
CREATE INDEX entity2document_nephro_cardio_kind_new ON entity2document_nephro_cardio (kind);
CREATE TABLE MeshTerm (id INT NOT NULL, meshId VARCHAR(255) NOT NULL, term VARCHAR(255) NOT NULL, created TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id));
CREATE INDEX meshTerm_meshId_index ON MeshTerm (meshId);
CREATE INDEX meshTerm_term_index ON MeshTerm (term);
CREATE TABLE ToxicEndpoint (id INT NOT NULL, kind VARCHAR(60) NOT NULL, uid VARCHAR(255) NOT NULL, sentenceId INT NOT NULL, entityId1 VARCHAR(255) NOT NULL, entityId2 VARCHAR(255) NOT NULL, qualifier VARCHAR(60) NOT NULL, created TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id));
CREATE INDEX toxicEndpoint_uid_index ON ToxicEndpoint (uid);
CREATE INDEX toxicEndpoint_entityId1_index ON ToxicEndpoint (entityId1);
CREATE INDEX toxicEndpoint_entityId2_index ON ToxicEndpoint (entityId2);
CREATE TABLE Gene2Abstract (id INT NOT NULL, abstracts_id INT DEFAULT NULL, gene_name VARCHAR(1024) NOT NULL, gene_id VARCHAR(255) NOT NULL, tax_id INT NOT NULL, tax_id_validated INT NOT NULL, hepval DOUBLE PRECISION DEFAULT NULL, patternCount DOUBLE PRECISION DEFAULT NULL, ruleScore DOUBLE PRECISION DEFAULT NULL, hepTermNormScore DOUBLE PRECISION DEFAULT NULL, hepTermVarScore DOUBLE PRECISION DEFAULT NULL, svmConfidence DOUBLE PRECISION DEFAULT NULL, toxicology INT DEFAULT NULL, biomarker INT DEFAULT NULL, created TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id));
CREATE INDEX IDX_A3B1B2A9D1A79CA4 ON Gene2Abstract (abstracts_id);
CREATE INDEX gene2Abstract_genename ON Gene2Abstract (gene_name);
CREATE INDEX gene2Abstract_geneid_index ON Gene2Abstract (gene_id);
CREATE INDEX gene2abstract_hepval_index ON Gene2Abstract (hepval);
CREATE INDEX gene2abstract_patterncount_index ON Gene2Abstract (patternCount);
CREATE INDEX gene2abstract_rulescore_index ON Gene2Abstract (ruleScore);
CREATE INDEX gene2abstract_heptermnormscore_index ON Gene2Abstract (hepTermNormScore);
CREATE INDEX gene2abstract_heptermvarscore_index ON Gene2Abstract (hepTermVarScore);
CREATE INDEX gene2abstract_svmconfidence_index ON Gene2Abstract (svmConfidence);
CREATE INDEX gene2abstract_toxicology_index ON Gene2Abstract (toxicology);
CREATE INDEX gene2abstract_biomarker_index ON Gene2Abstract (biomarker);
CREATE TABLE Entity2Abstract (id INT NOT NULL, abstracts_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, qualifier VARCHAR(60) NOT NULL, tagMethod VARCHAR(255) DEFAULT NULL, curation INT DEFAULT NULL, hepval DOUBLE PRECISION DEFAULT NULL, patternCount DOUBLE PRECISION DEFAULT NULL, ruleScore DOUBLE PRECISION DEFAULT NULL, hepTermNormScore DOUBLE PRECISION DEFAULT NULL, hepTermVarScore DOUBLE PRECISION DEFAULT NULL, svmConfidence DOUBLE PRECISION DEFAULT NULL, created TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id));
CREATE INDEX IDX_B5ED9DAD1A79CA4 ON Entity2Abstract (abstracts_id);
CREATE INDEX entity2Abstract_name ON Entity2Abstract (name);
CREATE INDEX entity2Abstract_qualifier ON Entity2Abstract (qualifier);
CREATE INDEX entity2Abstract_hepval ON Entity2Abstract (hepval);
CREATE INDEX entity2Abstract_svmconfidence ON Entity2Abstract (svmConfidence);
CREATE INDEX entity2Abstract_rulescore ON Entity2Abstract (ruleScore);
CREATE INDEX entity2Abstract_patterncount ON Entity2Abstract (patternCount);
CREATE INDEX entity2Abstract_heptermnormscore ON Entity2Abstract (hepTermNormScore);
CREATE INDEX entity2Abstract_heptermvarscore ON Entity2Abstract (hepTermVarScore);
CREATE INDEX entity2Abstract_qualifier_name ON Entity2Abstract (qualifier, name);
CREATE INDEX entity2Abstract_qualifier_name_hepval ON Entity2Abstract (qualifier, name, hepval);
CREATE SEQUENCE fos_user_id_seq INCREMENT BY 1 MINVALUE 1 START 1;
CREATE SEQUENCE documentold_nephro_cardio_id_seq INCREMENT BY 1 MINVALUE 1 START 1;
CREATE SEQUENCE DocumentWithMarker_id_seq INCREMENT BY 1 MINVALUE 1 START 1;
CREATE SEQUENCE DocumentWithCytochrome_id_seq INCREMENT BY 1 MINVALUE 1 START 1;
CREATE SEQUENCE Image_id_seq INCREMENT BY 1 MINVALUE 1 START 1;
CREATE SEQUENCE DocumentWithCompound_id_seq INCREMENT BY 1 MINVALUE 1 START 1;
CREATE SEQUENCE AbstractWithCompound_id_seq INCREMENT BY 1 MINVALUE 1 START 1;
CREATE SEQUENCE Abstracts_id_seq INCREMENT BY 1 MINVALUE 1 START 1;
CREATE SEQUENCE Marker_id_seq INCREMENT BY 1 MINVALUE 1 START 1;
CREATE SEQUENCE EntityRanking_id_seq INCREMENT BY 1 MINVALUE 1 START 1;
CREATE SEQUENCE tanimotovalues_new_id_seq INCREMENT BY 1 MINVALUE 1 START 1;
CREATE SEQUENCE GeneSpecie_id_seq INCREMENT BY 1 MINVALUE 1 START 1;
CREATE SEQUENCE Drugbank_id_seq INCREMENT BY 1 MINVALUE 1 START 1;
CREATE SEQUENCE MarkerType_id_seq INCREMENT BY 1 MINVALUE 1 START 1;
CREATE SEQUENCE Alias_id_seq INCREMENT BY 1 MINVALUE 1 START 1;
CREATE SEQUENCE GeneDictionary_id_seq INCREMENT BY 1 MINVALUE 1 START 1;
CREATE SEQUENCE GoTerm_id_seq INCREMENT BY 1 MINVALUE 1 START 1;
CREATE SEQUENCE MolecularMechanism_id_seq INCREMENT BY 1 MINVALUE 1 START 1;
CREATE SEQUENCE Specie_id_seq INCREMENT BY 1 MINVALUE 1 START 1;
CREATE SEQUENCE AdverseEffect_id_seq INCREMENT BY 1 MINVALUE 1 START 1;
CREATE SEQUENCE HepatotoxKeyword_id_seq INCREMENT BY 1 MINVALUE 1 START 1;
CREATE SEQUENCE Gene_id_seq INCREMENT BY 1 MINVALUE 1 START 1;
CREATE SEQUENCE CompoundMesh_id_seq INCREMENT BY 1 MINVALUE 1 START 1;
CREATE SEQUENCE CompoundDict_id_seq INCREMENT BY 1 MINVALUE 1 START 1;
CREATE SEQUENCE Enzyme_id_seq INCREMENT BY 1 MINVALUE 1 START 1;
CREATE SEQUENCE OrganTissue_id_seq INCREMENT BY 1 MINVALUE 1 START 1;
CREATE SEQUENCE HepatotoxTrigger_id_seq INCREMENT BY 1 MINVALUE 1 START 1;
CREATE SEQUENCE CypsUniprotRanking_id_seq INCREMENT BY 1 MINVALUE 1 START 1;
CREATE SEQUENCE CellType_id_seq INCREMENT BY 1 MINVALUE 1 START 1;
CREATE SEQUENCE Cytochrome_id_seq INCREMENT BY 1 MINVALUE 1 START 1;
CREATE SEQUENCE Structure_id_seq INCREMENT BY 1 MINVALUE 1 START 1;
CREATE SEQUENCE compound2marker2document_new_id_seq INCREMENT BY 1 MINVALUE 1 START 1;
CREATE SEQUENCE HepKeywordTermNorm2Document_id_seq INCREMENT BY 1 MINVALUE 1 START 1;
CREATE SEQUENCE cytochrome2document_new_id_seq INCREMENT BY 1 MINVALUE 1 START 1;
CREATE SEQUENCE Specie2Document_id_seq INCREMENT BY 1 MINVALUE 1 START 1;
CREATE SEQUENCE compound2term2document_new_id_seq INCREMENT BY 1 MINVALUE 1 START 1;
CREATE SEQUENCE HepKeywordTermVariant2Document_id_seq INCREMENT BY 1 MINVALUE 1 START 1;
CREATE SEQUENCE compound2cyp2document_new_id_seq INCREMENT BY 1 MINVALUE 1 START 1;
CREATE SEQUENCE entity2document_nephro_cardio_id_seq INCREMENT BY 1 MINVALUE 1 START 1;
CREATE SEQUENCE MeshTerm_id_seq INCREMENT BY 1 MINVALUE 1 START 1;
CREATE SEQUENCE ToxicEndpoint_id_seq INCREMENT BY 1 MINVALUE 1 START 1;
CREATE SEQUENCE Gene2Abstract_id_seq INCREMENT BY 1 MINVALUE 1 START 1;
CREATE SEQUENCE Entity2Abstract_id_seq INCREMENT BY 1 MINVALUE 1 START 1;
ALTER TABLE tanimotovalues_new ADD CONSTRAINT FK_E20FBD9740F16A48 FOREIGN KEY (idcompound1) REFERENCES CompoundDict (id) NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE tanimotovalues_new ADD CONSTRAINT FK_E20FBD97D9F83BF2 FOREIGN KEY (idcompound2) REFERENCES CompoundDict (id) NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE GeneSpecie ADD CONSTRAINT FK_29B1CC6838BEE1C3 FOREIGN KEY (gene_id) REFERENCES Gene (id) NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE GeneSpecie ADD CONSTRAINT FK_29B1CC68D5436AB7 FOREIGN KEY (specie_id) REFERENCES Specie (id) NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE CompoundDict ADD CONSTRAINT FK_88A1CD3C3DA5256D FOREIGN KEY (image_id) REFERENCES Image (id) NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE CompoundDict ADD CONSTRAINT FK_88A1CD3C2534008B FOREIGN KEY (structure_id) REFERENCES Structure (id) NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE compound2marker2document_new ADD CONSTRAINT FK_60CF12B6C33F7837 FOREIGN KEY (document_id) REFERENCES documentold_nephro_cardio (id) NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE HepKeywordTermNorm2Document ADD CONSTRAINT FK_1C19BCD0C33F7837 FOREIGN KEY (document_id) REFERENCES documentold_nephro_cardio (id) NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE cytochrome2document_new ADD CONSTRAINT FK_21C7FD7C33F7837 FOREIGN KEY (document_id) REFERENCES documentold_nephro_cardio (id) NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE Specie2Document ADD CONSTRAINT FK_B6E551C8C33F7837 FOREIGN KEY (document_id) REFERENCES documentold_nephro_cardio (id) NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE Specie2Document ADD CONSTRAINT FK_B6E551C8D5436AB7 FOREIGN KEY (specie_id) REFERENCES Specie (id) NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE compound2term2document_new ADD CONSTRAINT FK_87F99CECC33F7837 FOREIGN KEY (document_id) REFERENCES documentold_nephro_cardio (id) NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE HepKeywordTermVariant2Document ADD CONSTRAINT FK_A316E36BC33F7837 FOREIGN KEY (document_id) REFERENCES documentold_nephro_cardio (id) NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE compound2cyp2document_new ADD CONSTRAINT FK_80F82FB6C33F7837 FOREIGN KEY (document_id) REFERENCES documentold_nephro_cardio (id) NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE entity2document_nephro_cardio ADD CONSTRAINT FK_91F5304EC33F7837 FOREIGN KEY (document_id) REFERENCES documentold_nephro_cardio (id) NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE Gene2Abstract ADD CONSTRAINT FK_A3B1B2A9D1A79CA4 FOREIGN KEY (abstracts_id) REFERENCES Abstracts (id) NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE Entity2Abstract ADD CONSTRAINT FK_B5ED9DAD1A79CA4 FOREIGN KEY (abstracts_id) REFERENCES Abstracts (id) NOT DEFERRABLE INITIALLY IMMEDIATE;

